server:
  # host: localhost
  host: 0.0.0.0
  # host: 127.0.0.1
  port: 8080

db:
  host: localhost
  port: 5433
  name: auth
  user: postgres
  password: postgres
  ssl_mode: disable


logger:
  filename: app.log

rsa_keys:
  public: internal/config/keys/jwt-public.pem
  private: internal/config/keys/jwt-private.pem


kafka:
  host: 127.0.0.1
  port: 9092
  auth_topic_send: jwtCheckAnswer
  auth_topic_recieve: jwtCheckRequest
  user_signup_send: userSignUp


jaeger:
  host: localhost
  port: 6831
  service_name: auth-service
