server:
  # host: localhost
  host: 0.0.0.0
  port: 8004


db:
  host: localhost
  port: 5434
  name: admin
  user: postgres
  password: postgres
  ssl_mode: disable


logger:
  filename: app.log

kafka:
  host: localhost
  port: 9092
  partition: 0
  auth_topic_send: jwtCheckAnswer
  auth_topic_recieve: jwtCheckRequest
  season_topic_send: seasons
  dailyTasks_topic_send: dailyTasks
  gameSettings_topic_send: gameSettings

jaeger:
  host: localhost
  port: 6831
  service_name: admin-service

  




