server:
  host: localhost
  port: 8004


db:
  host: localhost
  port: 5434
  name: admin
  user: postgres
  password: postgres
  ssl_mode: disable




kafka:
  host: localhost
  port: 9092
  partition: 0
  auth_topic_send: jwtCheckAnswer
  auth_topic_recieve: jwtCheckRequest
  season_topic_send: seasons
  dailyTasks_topic_send: dailyTasks
  gameSettings_topic_send: gameSettings

  




