global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '172.17.0.1:8080'
    scrape_interval: 5s

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '172.17.0.1:8004'
    scrape_interval: 5s

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '172.17.0.1:8005'
    scrape_interval: 5s

  - job_name: 'core-service'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '172.17.0.1:8006'
    scrape_interval: 5s
