server:
  # host: localhost
  host: 0.0.0.0
  port: 8006

db:
  host: localhost
  port: 5435
  name: core
  user: postgres
  password: postgres
  ssl_mode: disable


logger:
  filename: app.log


kafka:
  host: localhost
  port: 9092
  partition: 1
  auth_topic_send: jwtCheckAnswer 
  auth_topic_recieve: jwtCheckRequest
  season_topic_recieve: seasons
  daily_task_topic_recieve: dailyTasks
  match_topic_recieve: match
  user_signup_recieve: userSignUp


redis:
  host: localhost
  port: 6379
  password: 
  db: 0