server:
  host: localhost
  port: 8005

logger:
  filename: app.log


clickhouse:
  host: localhost
  port: 9000
  name: game
  user: my_user
  password: my_password


kafka:
  host: localhost
  port: 9092
  partition: 2
  auth_topic_send: jwtCheckAnswer
  auth_topic_recieve: jwtCheckRequest
  gameSettings_topic_recieve: gameSettings
  match_topic_send: match


redis:
  host: localhost
  port: 6379
  password: 
  db: 0


random:
  api-key: ff9512b9-99c4-4b88-bf63-a40b27e13bb8
  api-url: https://api.random.org/json-rpc/2/invoke


jaeger:
  host: localhost
  port: 6831
  service_name: game-service


  




