# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "make && go build -o tmp/main ./cmd/auth"
  include_ext = ["go", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "docs"]

[watch]
  include_ext = ["go", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "docs"]